name: test
on: [push, pull_request]
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.23.2
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Make test.sh executable
      run: chmod +x test.sh
    - name: Run test.sh
      run: ./test.sh

